baseURL = "https://johnnyle12.github.io/FCJ-Workshop-Report/"
relativeURLs = true
canonifyURLs = true

theme = "hugo-theme-learn"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  description = ""
  author = "thienlh@thienlu.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[Languages]
  [Languages.en]
    title = "Internship Report"
    weight = 1
    languageName = "English"

    [[Languages.en.menu.shortcuts]]
      name = "<i class='fab fa-facebook'></i> AWS Study Group"
      identifier = "AWS Study Group FB"
      url = "https://www.facebook.com/groups/awsstudygroupfcj/"
      weight = 20

  [Languages.vi]
    title = "Báo cáo thực tập"
    weight = 2
    languageName = "Tiếng Việt"

    [[Languages.vi.menu.shortcuts]]
      name = "<i class='fab fa-facebook'></i> AWS Study Group"
      identifier = "AWS Study Group FB"
      url = "https://www.facebook.com/groups/awsstudygroupfcj/"
      weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
